version: '3.2'
services:
  api.desafio.dev:
    container_name: api.desafio.dev
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:80"
    volumes:
      - "./:/app"
  mysql.desafio.dev:
    container_name: mysql.desafio.dev
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
    command: mysqld --innodb-buffer-pool-size=64M
    ports:
      - "3407:3306"
  mongo.desafio.dev:
    container_name: mongo.desafio.dev
    image: mongo
    ports:
      - "27017:27017"
